name: orion-venv
channels:
  - conda-forge
  - pytorch
  - defaults
variables:
  CGO_ENABLED: 1
dependencies:
  - python>=3.9,<3.12  
  - go>=1.21
  - gcc 
  - pyyaml>=6.0
  - pytorch>=2.2.0
  - torchvision>=0.17.0
  - tqdm>=4.30.0
  - numpy>=1.21.0
  - scipy>=1.7.0,<=1.14.1
  - matplotlib>=3.1.0
  - h5py>=3.5.0
  - pip
  - pip:
    - -e .  