name: Build manylinux wheels

description: Builds Python 3.[x] wheels for manylinux2014.

inputs:
  python-version:
    description: 'Python version to build for (e.g. 3.9, 3.10)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Go
      shell: bash
      run: |
        curl -L https://go.dev/dl/go1.21.6.linux-amd64.tar.gz -o go.tar.gz
        tar -C /usr/local -xzf go.tar.gz
        echo "PATH=/usr/local/go/bin:$PATH" >> $GITHUB_ENV
    
    - name: Build manylinux wheel for Python ${{ inputs.python-version }}
      shell: bash
      run: |
        # Replace python path using version (e.g "3.9" -> "cp39-cp39")
        PYVER="${{ inputs.python-version }}"
        PYVER_NO_DOT="${PYVER//./}"
        PYBIN="/opt/python/cp${PYVER_NO_DOT}-cp${PYVER_NO_DOT}/bin"
        
        if [ ! -d "$PYBIN" ]; then
          echo "Python path not found: $PYBIN"
          echo "Unsupported Python version: $PYVER"
          exit 1
        fi
        
        "${PYBIN}/pip" install build
        "${PYBIN}/python" -m build --wheel