name: 'Convert to manylinux'
description: 'Converts a Linux wheel to a manylinux-compatible wheel'

inputs:
  wheel-dir:
    description: 'Directory containing the wheel files'
    required: false
    default: 'dist'
  platform:
    description: 'Target manylinux platform'
    required: false
    default: 'manylinux2014_x86_64'

runs:
  using: composite
  steps:
    - name: Convert to manylinux wheel
      shell: bash -l {0}
      run: |
        # Install tool
        pip install auditwheel
        
        # Find any Linux wheel
        WHEEL_PATH=$(find ${{ inputs.wheel-dir }} -name "*linux*.whl")
        
        # Skip if no Linux wheel found
        if [ -z "$WHEEL_PATH" ]; then
          echo "No Linux wheel found, skipping manylinux conversion"
          exit 0
        fi
        
        # Debug wheel information
        echo "===== WHEEL INFORMATION ====="
        auditwheel show "$WHEEL_PATH" --verbose
        
        # Convert to manylinux
        echo "Converting $WHEEL_PATH to ${{ inputs.platform }}"
        TMP_DIR="${{ inputs.wheel-dir }}/manylinux"
        mkdir -p "$TMP_DIR"
        
        # Try manylinux repair with verbose output
        echo "===== REPAIR ATTEMPT ====="
        if ! auditwheel repair "$WHEEL_PATH" --plat ${{ inputs.platform }} -w "$TMP_DIR" --verbose; then
          echo "===== FALLBACK TO NEWER PLATFORM ====="
          # If manylinux2014 fails, try with manylinux_2_17
          if [[ "${{ inputs.platform }}" == "manylinux2014_x86_64" ]]; then
            echo "Attempting fallback to manylinux_2_17_x86_64"
            auditwheel repair "$WHEEL_PATH" --plat manylinux_2_17_x86_64 -w "$TMP_DIR" --verbose
          fi
        fi
        
        # Check if any repaired wheel was created
        REPAIRED_WHEELS=$(find "$TMP_DIR" -name "*.whl")
        if [ -z "$REPAIRED_WHEELS" ]; then
          echo "Failed to repair wheel, keeping original"
        else
          # Replace original wheel with manylinux version
          mv "$TMP_DIR"/*.whl ${{ inputs.wheel-dir }}/
          rm "$WHEEL_PATH"
        fi
        
        # Clean up
        rm -rf "$TMP_DIR"