name: 'Setup environment'
description: 'Sets up build dependencies including Python and Go'

inputs:
  python-version:
    required: true
    description: 'Python version to use'
  architecture:
    required: false
    description: 'CPU architecture (arm64 or x64)'
    default: 'x64'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        architecture: ${{ inputs.architecture }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
    
    - name: Configure platform-specific settings
      shell: bash
      run: |
        # macOS-specific Go configuration
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          if [[ "${{ inputs.architecture }}" == "arm64" ]]; then
            echo "GOARCH=arm64" >> $GITHUB_ENV
          else
            echo "GOARCH=amd64" >> $GITHUB_ENV
          fi
        fi
        
        # Configure Go to disable VCS stamping
        echo "GOFLAGS=-buildvcs=false" >> $GITHUB_ENV