name: 'build manylinux wheels'
description: 'builds manylinux wheels for orion'
inputs:
  python-version:
    description: 'python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
    
    - name: install uv
      shell: bash
      run: |
        yum install -y python3-pip
        python${{ inputs.python-version }} -m pip install uv
        uv --version
    
    - name: build package 
      shell: bash
      run: |
        uv venv --python ${{ inputs.python-version }}
        source .venv/bin/activate
        uv pip install auditwheel
        uv build --sdist --wheel --out-dir dist

        echo "Contents of the wheel file:"
        unzip -l dist/*.whl
    
    - name: use auditwheel to support earlier manylinux
      shell: bash
      run: |
        source .venv/bin/activate
        auditwheel repair dist/*.whl --plat manylinux2014_x86_64

        echo "Contents of the wheelhouse directory:"
        ls -l wheelhouse/
        
