name: 'build manylinux wheels'
description: 'builds manylinux wheels for orion'
inputs:
  python-version:
    description: 'python version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: set up go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
    
    - name: install uv
      shell: bash
      run: |
        pip install uv
        uv --version
    
    - name: build package 
      shell: bash
      run: |
        uv venv --python ${{ inputs.python-version }}
        source .venv/bin/activate
        uv pip install setuptools wheel build auditwheel
        
        python setup.py build # generates .so/dylib/dll file first
        uv build --sdist --wheel --out-dir dist
    
    - name: convert to manylinux with auditwheel
      shell: bash
      run: |
        auditwheel repair dist/*.whl --plat ${{ matrix.manylinux }}
        ls -l dist
        
