name: 'Manylinux Builder with Go'
description: 'Builds Python packages with manylinux and includes Go installation'
inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.9'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'
    
    - name: Set up Python
      shell: bash
      run: |
        # Use the proper Python version based on input
        PYTHON_BIN="/opt/python/cp$(echo ${{ inputs.python-version }} | sed 's/\.//')/bin/python"
        echo "Using Python: $PYTHON_BIN"
        $PYTHON_BIN -m pip install --upgrade pip
    
    - name: Install UV
      shell: bash
      run: |
        $PYTHON_BIN -m pip install uv
    
    - name: Build package
      shell: bash
      run: |
        $PYTHON_BIN setup.py build # generates .so/dylib/dll file first
        $PYTHON_BIN -m uv build --sdist --wheel --out-dir dist