name: Build manylinux2014 wheel

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
        description: 'Python version to build for (e.g., 3.9, 3.10)'
      wheel-dir:
        required: false
        type: string
        default: 'dist'
        description: 'Directory to output wheels to'
    outputs:
      wheel-path:
        description: 'Path to the built manylinux wheel'
        value: ${{ jobs.build-manylinux.outputs.wheel-path }}

jobs:
  build-manylinux:
    runs-on: ubuntu-latest
    outputs:
      wheel-path: ${{ steps.find-wheel.outputs.wheel-path }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build manylinux wheel
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .github/docker/Dockerfile.manylinux
          push: false
          outputs: type=local,dest=./manylinux-output
          build-args: |
            PYTHON_VERSION=${{ inputs.python-version }}

      - name: Copy wheels to specified directory
        run: |
          mkdir -p ${{ inputs.wheel-dir }}
          cp -r manylinux-output/* ${{ inputs.wheel-dir }}/

      - name: Find built wheel
        id: find-wheel
        run: |
          WHEEL_PATH=$(find ${{ inputs.wheel-dir }} -name "*manylinux*.whl" | head -n 1)
          echo "wheel-path=$WHEEL_PATH" >> $GITHUB_OUTPUT
          echo "Built manylinux wheel: $WHEEL_PATH"