comment: Config for LoLA from Figure 3 of https://arxiv.org/pdf/1812.10659

ckks_params: 
  LogN: 16  #originally 16
  LogQ: [60, 30, 30, 30, 30, 30, 30]
  LogP: [60, 60]
  LogScale: 30
  H: 8192
  RingType: Standard

orion:
  margin: 2 # >= 1
  embedding_method: hybrid # [hybrid, square]
  backend: heongpu # [lattigo, openfhe, heaan, heongpu]

  fuse_modules: true
  debug: false

  diags_path: ../data/diagonals.h5 # "path/to/diags" | ""
  keys_path: ../data/keys.h5 # "path/to/keys" | ""
  io_mode: none # "load" | "save" | "none"
