comment: Config for LoLA from Figure 3 of https://arxiv.org/pdf/1812.10659

ckks_params: 
  LogN: 16
  LogQ: [39, 32, 32, 32, 32]
  LogP: [39, 39]
  LogScale: 39
  H: 8192
  RingType: ConjugateInvariant

orion:
  margin: 2 # >= 1
  embedding_method: hybrid # [hybrid, square]
  backend: heongpu # [lattigo, openfhe, heaan, heongpu]

  fuse_modules: true
  debug: false

  diags_path: ../data/diagonals.h5 # "path/to/diags" | ""
  keys_path: ../data/keys.h5 # "path/to/keys" | ""
  io_mode: none # "load" | "save" | "none"
