comment: "ResNet Parameter Set"

ckks_params:
  LogN: 13
  LogQ: [60, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30]    #need 26 total for bootstrapping(including 60)
  LogP: [60, 60]
  LogScale: 30
  H: 192
  RingType: standard

boot_params:
  LogP: [61, 61, 61, 61, 61, 61, 61, 61]

orion:
  margin: 2 # >= 1
  embedding_method: hybrid # [hybrid, square]
  backend: heongpu # [lattigo, openfhe, heaan]

  fuse_modules: true
  debug: true

  diags_path: ../data/diagonals.h5 # "path/to/diags" | ""
  keys_path: ../data/keys.h5 # "path/to/keys" | ""
  io_mode: none # "load" | "save" | "none"