name: Build and Publish

on:
  push:
    branches: [main, dev]
  pull_request:

permissions:
  contents: write

jobs:
  build_wheels:
    name: Build wheels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          # Correctly format Python version for cibuildwheel
          # For example, "3.11" needs to become "311" for cp311
          CIBW_BUILD: "cp$(echo ${{ matrix.python-version }} | tr -d '.')-manylinux_x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          # Skip building PyPy wheels
          CIBW_SKIP: "pp*"
          # Skip testing the built wheels (if you want to test, you can remove this)
          CIBW_TEST_SKIP: "*"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python${{ matrix.python-version }}-manylinux-wheels
          path: ./wheelhouse/*.whl