name: Build and Publish

on:
  push:
    branches: [main, dev]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and run Docker image
        uses: docker/build-push-action@v6
        with:
          context: .github/docker
          file: .github/docker/Dockerfile
          push: false
          load: true
          tags: wheel-builder:latest
      
      - name: Run wheel build
        run: |
          docker run --rm \
            -e PYTHON_VERSION=${{ matrix.python-version }} \
            -v ${{ github.workspace }}:/workspace \
            wheel-builder:latest
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: python${{ matrix.python-version }}-manylinux-wheels
          path: dist/